name: Build Jekyll site
on:
  push:
    branches: ["master"]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5
      - name: Build
        uses: actions/jekyll-build-pages@44a6e6beabd48582f863aeeb6cb2151cc1716697 # v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
  crawl:
    runs-on: ubuntu-latest
    needs: deploy
    env:
      GH_TOKEN: ${{ secrets.CHAT_SEARCH_CRAWL_TOKEN }}
    steps:
      - name: Crawl
        run: gh workflow run crawl.yml -R hemslo/chat-search -f sitemap-url=https://hemslo.io/sitemap.xml
