name: Build and deploy Jekyll site

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
  crawl:
    runs-on: ubuntu-latest
    needs: deploy
    env:
      GH_TOKEN: ${{ secrets.CHAT_SEARCH_CRAWL_TOKEN }}
    steps:
      - name: Crawl
        run: gh workflow run crawl.yml -R hemslo/chat-search -f sitemap-url=https://hemslo.io/sitemap.xml
